@startuml
'https://plantuml.com/activity-diagram-beta
title Login Activity Diagram

start

:Submit username and password;
:Validate username;
:Validate password;
fork
:Generate JWT;
fork again
:Generate Refresh Token;
end fork
:Return JWT and Refresh Token;

stop

@enduml
