@startuml
'https://plantuml.com/activity-diagram-beta
title Check Bookings Activity Diagram

|Buyer|
start
:Navigate to bookings page;

|System|
:Display all booking requests and confirmations;

|Buyer|
:View booking status (confirmed or pending);

stop

@enduml
