@startuml
'https://plantuml.com/sequence-diagram
title Logout Sequence Diagram

actor User
participant System
participant Database
User -> System: Trigger logout action
System -> Database: Invalidate refresh token
System -> User: Revoke JWT

@enduml